apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazon-clone
  template:
    metadata:
      labels:
        app: amazon-clone
    spec:
      containers:
        - name: web
          image: yourdockerhub/amazon-clone
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: amazon-clone-service
spec:
  type: NodePort
  selector:
    app: amazon-clone
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001
